### ISSUE TITLE
[Makefile] make 실행 시 에러 발생 관련 해결 제안

### ISSUE THREAD

**Issue by OZestina** [42Seoul-Tea42/matcha#1]
### 서론
matcha 레포의 깃 pull 받아서 실행해 보는데, make 시 하기의 내용이 터미널에 뜨는 것을 확인했습니다.

> git submodule update --init --recursive
git submodule update --remote
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'backend'
make: *** [default] Error 1

### 본론
검색해보니 기본 브랜치의 이름이 기존에 master였다가 main으로 변경된 것과 관련한 문제인 것 같습니다. [참고 링크](https://stackoverflow.com/a/71063106)
Tea42 org의 모든 레포의 기본 브랜치는 main으로 생성된 상태입니다.
-b 옵션으로 브랜치명을 줄 수 있습니다
> git submodule add -b branch_name URL_to_Git_repo optional_directory_rename

### 결론
하여 현재 Makefile의 .gitmodules 부분을 다음과 같이 변경하는 것을 제안합니다.
(변경 명령어로 위의 메시지가 뜨지 않는 것을 확인했습니다)
`$(foreach submodule, $(SUBMODULES), git submodule add -b main $(submodule);)`

### 참고내용
메시지가 뜨더라도 각 레포에서 클론은 제대로 받아오는 것 같습니다.
단순 경고 메시지인지 추후 에러 발생이 가능한 부분인지는 명확하지 않습니다.

**Comment by JaeJunday** [comment]
추후 에러 발생이 가능성은 낮아보입니다. 
확인하고 수정하겠습니다. 
해결법을 같이 찾아주셔서 감사합니다.
